version: "3.8"
services: 
    db:
        image: mysql:5.7
        volumes: 
            - db_data:/varlib/mysql
        restart: always
        environment:
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
            MYSQL_ROOT_PASSWORD: rootwordpress
        ports: 
            - 6000:3306
    wordpress:
        container_name: 'wordpress-local'
        depends_on:
            - db
        image: wordpress:latest
        ports:
            - 5000:80
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
            WORDPRESS_DB_NAME: wordpress
        volumes:
            - ./wordpress:/var/www/html
volumes:
    db_data: {}
        