version: '3.8'
services:
    web:
        build:
          context: .
          dockerfile: Dockerfile-create
          #dockerfile: Dockerfile-serve
          #dockerfile: Dockerfile-build
        stdin_open: true
        tty: true
        ports: 
            - "8080:8080"
        volumes:
            - ".:/app"